---
title: "Homework"
author: "Noah W.K. Mattheis"
date: "2025-01-22"
output: 
  html_document: 
    highlight: tango
    theme: cosmo
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


# Homework Links


#### Week 1
[Homework 1](https://github.com/NoahMattheis)

This assignment was about setting up GitHub Page


#### Week 2
[Homework 2](https://noahmattheis.github.io/MattheisBIOL6100/index.html)

[Homework 21](Homework2.html)

This assignment was about setting up links to the website - both links to another website and links to other RMD/HTML pages made within the project

#### Week 3
[Homework 3](Homework3.html)

This assignment is based around utilizing RegEx expressions for lists and data sets

#### Week 4
[Homework 4](Homework4.html)

This assignment is based around manipulation and understanding of Atomic Vectors/Lists

#### Week 5
[Homework 5](Homework5.html)

This assignment revolves around creation and manipulation of data in lists and data frames

#### Week 6
[Homework 6](Homework6.html)

This assignment revolves around creation of a fake data set to use in statistical analysis and testing. This assignment focuses on data creation, testing, and for loop mechanics, with some if statements as well

#### Week 7
[Homework 7](Homework7.html)

This assignment revolves around creating a data set and then using piping and other tidyverse/dplyr functions to manipulate said data set

#### Week 8
[Homework 8](Homework8.html)

This assignment revolves around comparing histograms of continuous or integer data types to respective probability density function for different statistical distributions

#### Week 9
[Homework 9](NWKM_Homework9_BIOL6100.zip)

This assignment revolves around downloading a series of data sets online, creating pseudo-code/user-made-functions to clean the data, obtain certain counts, regression statistics, and histograms
